name: Dev
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install -g lib.cli
      - run: 'echo "ACCESS_TOKEN=$AUTOCODE_ACCESS_TOKEN" > ~/.librc'
        shell: bash
        env:
          AUTOCODE_ACCESS_TOKEN: ${{ secrets.AUTOCODE_ACCESS_TOKEN }}
      - run: |-
          cat <<EOF > env.json
          {
            "dev": {
              "SHOPIFY_PARTNER_API_TOKEN": "$SHOPIFY_PARTNER_API_TOKEN",
              "SLACK_CHANNEL": "#general",
              "SHOPIFY_PARTNER_ID": "1573297",
              "SHOPIFY_APP_ID": "4376027"
            }
          }
          EOF
        env:
          SHOPIFY_PARTNER_API_TOKEN: ${{ secrets.SHOPIFY_PARTNER_API_TOKEN }}
      - run: lib up dev
